# Generated by Django 4.1.7 on 2023-03-05 17:28

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hitcount', '0005_alter_blacklistip_id_alter_blacklistuseragent_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('avatar', models.ImageField(upload_to='careers')),
                ('country', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('type_work', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('requrements', ckeditor.fields.RichTextField()),
                ('views', models.ManyToManyField(blank=True, related_name='hit_count_generic_relation', to='hitcount.hitcount')),
            ],
            options={
                'verbose_name': 'Career',
                'verbose_name_plural': 'Careers',
            },
        ),
        migrations.CreateModel(
            name='Instagramlinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='instagram')),
                ('link', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Instagram Link',
                'verbose_name_plural': 'Instagram Links',
            },
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.ImageField(upload_to='managements')),
                ('position', models.CharField(max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('reception_days', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
            ],
            options={
                'verbose_name': 'Management',
                'verbose_name_plural': 'Managements',
            },
        ),
        migrations.CreateModel(
            name='Representation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.ImageField(upload_to='representations')),
                ('icon_flag', models.ImageField(upload_to='representations')),
                ('country', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=100)),
            ],
            options={
                'verbose_name': 'Representation',
                'verbose_name_plural': 'Representations',
            },
        ),
        migrations.CreateModel(
            name='SendCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('cv', models.FileField(upload_to='cv')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.career')),
            ],
            options={
                'verbose_name': 'Send CV',
                'verbose_name_plural': 'Send CVs',
            },
        ),
    ]
