# Generated by Django 4.1.7 on 2023-03-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_instagramlinks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instagramlinks',
            options={},
        ),
        migrations.AlterField(
            model_name='instagramlinks',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='instagram'),
        ),
        migrations.AlterField(
            model_name='instagramlinks',
            name='link',
            field=models.CharField(max_length=100),
        ),
    ]
