# Generated by Django 4.1.7 on 2023-03-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_instagramlinks_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramlinks',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
