# Generated by Django 4.1.7 on 2023-03-06 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_alter_instagramlinks_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instagramlinks',
            new_name='Instagramlink',
        ),
    ]
